services:

  http-server-projeto-korp:
    build:
      context: ./app
    container_name: http-server-projeto-korp
    networks:
      - korp-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - http-server-projeto-korp
    networks:
      - korp-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - korp-network

  grafana:
    image: grafana/grafana

    container_name: grafana

    ports:
      - "${GRAFANA_PORT}:3000"

    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}

    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

    depends_on:
      - prometheus

    networks:
      - korp-network

networks:
  korp-network:
    driver: bridge