{
 "title": "Projeto Korp Dashboard",
 "tags": [ "korp" ],
 "panels": [
  {
   "title": "Total de Requisições",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "Disponibilidade",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"http-server-projeto-korp\"}"
    }
   ]
  },
  {
   "title": "Requisições ao Longo do Tempo",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  }
 ]
}