---
- name: Provisionar Projeto Korp
  hosts: servers
  become: true

  vars:
    project_dir: /opt/projeto-korp

  tasks:

    - name: Atualizar cache do apt
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name:
          - docker.io
        state: present

    - name: Habilitar Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Criar diretório do projeto
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Copiar projeto
      copy:
        src: ../
        dest: "{{ project_dir }}"

    - name: Subir ambiente Docker
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        build: always
        state: present

    - name: Aguardar API iniciar
      wait_for:
        host: localhost
        port: 80
        timeout: 60

    - name: Validar endpoint da API
      uri:
        url: http://localhost/projeto-korp
        return_content: true
      register: api_response

    - name: Exibir resposta da API
      debug:
        var: api_response.json

    - name: Validar Prometheus
      uri:
        url: http://localhost:9090/-/healthy
      register: prometheus_response

    - name: Validar Grafana
      uri:
        url: http://localhost:3000/api/health
      register: grafana_response

    - name: Exibir status Prometheus
      debug:
        var: prometheus_response.status

    - name: Exibir status Grafana
      debug:
        var: grafana_response.json