---
- name: Provisionar Projeto Korp
  hosts: servers
  connection: local

  vars:
    project_dir: /mnt/c/Users/Gabriel/OneDrive/Documentos/projeto-korp

  tasks:

    - name: Subir ambiente Docker
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        build: always
        state: present

    - name: Aguardar API iniciar
      wait_for:
        host: localhost
        port: 80
        timeout: 60

    - name: Validar endpoint da API
      uri:
        url: http://localhost/projeto-korp
        return_content: true
      register: api_response

    - name: Exibir resposta da API
      debug:
        var: api_response.json

    - name: Validar Prometheus
      uri:
        url: http://localhost:9090/-/healthy
      register: prometheus_response

    - name: Aguardar Grafana iniciar
      wait_for:
        host: localhost
        port: 3000
        timeout: 120

    - name: Validar Grafana
      uri:
        url: http://localhost:3000/api/health
        status_code: 200
      register: grafana_response
      retries: 10
      delay: 5
      until: grafana_response.status == 200

    - name: Exibir status Prometheus
      debug:
        var: prometheus_response.status

    - name: Exibir status Grafana
      debug:
        var: grafana_response.json